//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Salaries = new HashSet<Salary>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int role_id { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Salary> Salaries { get; set; }
    }
}
