//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Id { get; set; }
        public int employee_id { get; set; }
        public int currency_id { get; set; }
        public int annual_amount { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
